config/routes.rb
AmktClient::Application.routes.draw do

  resources :licenses do
    collection do
      get 'bought'
      get 'notbought'
      get 'pivot'
      get 'timeline'
      get 'geochart'
      get 'filter'
      post 'filter'
      get 'sort'
      get 'group'
      get 'import'
      post 'do_import'
      get  'import_stream'
      get 'sales'
      post 'sales_update'
      get  'sales_data'
    end
  end

  root :to => redirect('/licenses')
  

end

app/controllers/licenses_controller.rb
require "net/https"
require "uri"

class LicensesController < ApplicationController
  def defaults
    @fromDate = Date.new(2012,04,28)
    @toDate = Date.new(2012,12,28)
    if (session[:fromDate] && session[:toDate])
      @fromDate = date session[:fromDate]
      @toDate = date session[:toDate]
    end
    @all_editions = License.all_editions
    @current_action = action_name
  end
  def licenses
    defaults
    filter = {}
    if (session[:editions])
      filter['edition'] = session[:editions].keys
    end
    if (session[:fromDate] && session[:toDate])
      filter[:startDate] = @fromDate .. @toDate
    end
    @licenses = License.where(filter)
    if (session[:c])
      @licenses = @licenses.joins(:technicalContactAddress).where('addresses.country' => session[:c].keys)
    end
    if (session[:sort])
      # otherwise column does not exist in postresql
      @licenses = @licenses.order('"licenses".'+"\"#{session[:sort]}\"")
    end
    @licenses = @licenses.includes([:technicalContact, :technicalContactAddress])
    if block_given?
      @licenses = yield @licenses
    end
    @licenses.map {|license| license['price'] = License.price license}
  end

  def date param
    Date.civil(param[:year].to_i, param[:month].to_i, param[:day].to_i)
  end

  def update_session param
    if (params[param]) 
      session[param] = params[param]
    end
  end

  def restful
    update_session :editions
    update_session :c
    update_session :fromDate
    update_session :toDate
    update_session :sort
    update_session :group_by
    if (params[:editions] != session[:editions] ||
        params[:c] != session[:c] ||
        params[:fromDate] != session[:fromDate] ||
        params[:toDate] != session[:toDate] ||
        params[:sort] != session[:sort] ||
        params[:group_by] != session[:group_by])
      redirect_to :action => action_name,
        :editions => session[:editions], :c => session[:c],
        :fromDate => session[:fromDate], :toDate => session[:toDate],
        :sort => session[:sort], :group_by => session[:group_by]
      return false
    else
      return true
    end
  end

  def restful_redirect
    redirect_to :action => params[:return_to],
      :editions => session[:editions], :c => session[:c],
      :fromDate => session[:fromDate], :toDate => session[:toDate],
      :sort => session[:sort], :group_by => session[:group_by]
  end

  def filter
    session[:editions] = params[:editions]
    session[:c] = params[:c]
    session[:fromDate] = params[:fromDate]
    session[:toDate] = params[:toDate]
    restful_redirect
  end

  def sort
    session[:sort] = params[:sort]
    restful_redirect
  end

  def group
    session[:group_by] = params[:group_by]
    restful_redirect
  end

  def index
    restful or return false
    licenses
    geo
    @sum = @licenses.reduce(0) {|sum, license| sum + (license['price'] || 0)}
    @all_countries = @geo.keys
    @supported_countries = License.supported_countries.reject { |c, _| @all_countries.index(c) == nil}
  end

  def bought
    index or return
    @licenses = @licenses.find_all {|license| License.paid_licenseTypes.index(license['licenseType'])}
    @licenses = @licenses.sort_by {|license| license['startDate']}
    render :action => 'index'
  end

  class OrganisationNameOrTechnicalEmailKey
    attr_reader :organisationName
    attr_reader :technicalEmail

    def initialize organisationName, technicalEmail, hashArray
      @organisationName = organisationName
      @technicalEmail = technicalEmail
      @hashArray = hashArray
    end

    def == other
       self.organisationName == other.organisationName ||
         self.technicalEmail == other.technicalEmail
    end
    
    def eql? other
      return self == other
    end
    
    def hash
      i = @hashArray.index self 
      if !i
        i = @hashArray.size
        @hashArray[i] = self
      end
      return i
    end
  end

  def notbought
    index or return
    hashArray = Array.new
    @licenses_map = @licenses.reduce({}) do |m, license|
      organisationName = license.organisationName || 'N/A'
      technicalEmail = license.technicalContact.email || 'N/A'
      key = OrganisationNameOrTechnicalEmailKey.new organisationName, technicalEmail, hashArray
      licenses = m[key] || []
      i = licenses.index {|l| l['edition'] == license['edition']}
      if (!i)
        license['count'] = 1
        licenses <<= license
      elsif licenses[i]['startDate'] < license['startDate']
        license['count'] = licenses[i]['count'] + 1
        licenses[i] = license
      else
        licenses[i]['count'] += 1
      end
      m[key] = licenses
      m
    end
    @licenses_map = @licenses_map.select do |organisationName, licenses|
      licenses.index {|license| license['edition'] != 'Evaluation'} == nil
    end
    @licenses = @licenses_map.values.flatten 1
    @licenses = @licenses.find_all {|license| license['endDate'] <= '2012-11-30' && license['endDate'] >= '2012-11-01'}
    @licenses = @licenses.sort_by {|license| license['organisationName']} 
    @sum = 0
    render :action => 'index'
  end

  def pivot_licenses
    licenses
=begin
    do |query| 
      case session[:group_by]
      when 'week'
        if (Rails.env.production?)
          # http://stackoverflow.com/questions/7171561/strftime-in-sqlite-convert-to-postgres
          week = 'extract(week from date("licenses"."startDate"))'
          year = 'extract(year from date("licenses"."startDate"))'
        else
          week = 'strftime("%W", date(startDate))'
          year = 'strftime("%Y", date(startDate))'
        end
        query = query.select("edition, count(*) count, #{week} \"week\", #{year} \"year\"").group(:year, :week, :edition)
      else
        query
      end
    end
=end
    @total = Hash[@all_editions.map {|edition, price| [edition, 0]}]
    @amount = Hash[@all_editions.map {|edition, price| [edition, 0]}]
    @pivot = @licenses.reduce({}) do |m, row|
      if session[:group_by]
        date = Date.parse row['startDate']
        startDate = Date.commercial date.year, date.cweek, 1
      else
        startDate = row['startDate']
      end
      record = m[startDate] || {}
      edition = row['edition']
      record[edition] = (row['count'] || 1) + (record[edition] || 0)
      m[startDate] = record
      @total[edition] += row['count'] || 1
      @amount[edition] += row['price']
      m
    end
  end

  def pivot
    respond_to do |format|
      format.html do
        restful
        pivot_licenses
      end
      format.json do
        pivot_licenses
        json = { :total => @total, :amount => @amount}
        render :json => json
      end
    end
  end

  def timeline
    respond_to do |format|
      format.html do
        restful
        defaults
        @all_editions = License.all_editions
      end
      format.json do
        pivot_licenses
        json = { :all_editions => session[:editions] || @all_editions,
          :pivot => @pivot}
        render :json => json
      end
    end
  end

  def geo_licenses
    licenses
    geo
  end

  def geo
    @geo = @licenses.reduce({}) do |m, row|
      country = row.technicalContactAddress.country || 'N/A'
      m[country] = 1 + (m[country] || 0)
      m
    end
    @geo = Hash[@geo.sort_by {|country, count| country}]
  end

  def geochart
    respond_to do |format|
      format.html do
        restful
        defaults
      end
      format.json do
        geo_licenses
        json = { :geo => @geo}
        render :json => json
      end
    end
  end

  def import
    @vendor = flash[:vendor]
    @log = flash[:log] || Array.new
    if env['SERVER_SOFTWARE'] !~ /Unicorn/
      import_func flash[:amkt_cookie] {|log| @log = log}
      flash.delete :amkt_cookie
    end
    # see https://github.com/rails/rails/blob/master/actionpack/lib/action_cont
    # not possible with haml
    #render :stream => true
  end

  def import_func amkt_cookie
    if amkt_cookie
      csv = get_licenses amkt_cookie
      #csv = File.read('licenseReport.csv')
      if (csv)
        yield License.import(csv)
      end
    end
  end

  def import_stream
    amkt_cookie = params[:amkt_cookie]
    self.response.headers['Last-Modified'] = Time.now.to_s
    self.response_body = Enumerator.new do |y|
      import_func amkt_cookie do |log|
        log.each do |license|
          y << '<li>' + license.to_s.gsub(/</, '&lt;').gsub(/>/,'&gt;') + '</li>'
        end
      end
    end
  end

  def amkt_http uri
    proxy_addr = nil
    proxy_port = nil
    proxy_url = ENV['https_proxy']
    if (proxy_url)
      proxy = URI.parse(proxy_url)
      proxy_addr = proxy.host
      proxy_port = proxy.port
    end
    http = Net::HTTP.start(uri.host, uri.port, proxy_addr, proxy_port,
      :use_ssl => true, :verify_mode => OpenSSL::SSL::VERIFY_NONE)
    http
  end

  def amkt_authenticate username, password
    uri = URI.parse("https://marketplace.atlassian.com/login")
    request = Net::HTTP::Post.new(uri.request_uri)
    request.set_form_data({:redirect => '', :username => username, :password => password})
    response = amkt_http(uri).request(request)
    auth = (/\/login\W/ !~ response['Location'])
    if auth && block_given?
      yield response['set-cookie']
    end
    auth
  end
  
  def get_licenses cookie
    uri = URI.parse("https://marketplace.atlassian.com/manage/vendors/120/licenseReport")
    request = Net::HTTP::Get.new(uri.request_uri, {'Cookie' => cookie})
    response = amkt_http(uri).request(request)
    if (response.code == '200')
      response.body.force_encoding("UTF-8")
    else
      @log << [response.code, response.body, response['Location']]
      false
    end
  end

  def authentication store
    contact = Contact.new params[:vendor]
    if !amkt_authenticate(contact.email, contact.password) {|cookie| store[:amkt_cookie] = cookie}
      flash[:warning] = "Login incorrect"
    end
    contact
  end

  def do_import
    @log = Array.new
    flash[:vendor] = authentication(flash)

app/views/licenses/_filter.html.haml
= form_tag filter_licenses_path, :method => :post do
  = hidden_field_tag 'return_to', @current_action
  Include:<br/>
  Editions: 
  - @all_editions.each do |edition, price|
    = check_box_tag "editions[#{edition}]", 1, session[:editions] && session[:editions].key?(edition)
    = edition
  <br/>
  From:
  = select_date @fromDate, :prefix => 'fromDate'
  To:
  = select_date @toDate, :prefix => 'toDate'
  <br/>
  - if (defined? countries)
    Countries (#{link_to 'All', filter_licenses_path(:edition => session[:editions], |
    :fromDate => session[:fromDate], :toDate => session[:toDate], |
    :return_to => @current_action)}/#{link_to 'Supported', filter_licenses_path( :edition => session[:editions], |
    :fromDate => session[:fromDate], :toDate => session[:toDate], :c => @supported_countries, |
    :return_to => @current_action)}): |
    - @geo.each do |country, num_of_licenses|
      = check_box_tag "c[#{country}]", 1, session[:c] && session[:c].key?(country)
      #{country}&nbsp;(#{num_of_licenses})
    <br/>

  = submit_tag 'Refresh', :id => 'licenses_submit'
      

app/views/licenses/_group.html.haml
<b>Group By:</b>
- if session[:group_by] == 'week'
  = link_to  'WEEK', group_licenses_path(:return_to => @current_action)
- else
  = link_to  'week', group_licenses_path(:group_by => 'week', :return_to => @current_action)

app/views/licenses/_nav.html.haml
#{link_to 'Index', licenses_path}(#{link_to 'Bought', bought_licenses_path}/#{link_to 'Notbought', notbought_licenses_path})
= link_to 'Pivot', pivot_licenses_path
= link_to 'Timeline', timeline_licenses_path
= link_to 'Geo Chart', geochart_licenses_path
= link_to 'Import', import_licenses_path
= link_to 'REST API', sales_licenses_path

app/views/licenses/chart.html.haml
- content_for(:head) do
  = javascript_include_tag 'http://www.google.com/jsapi'
  = javascript_include_tag :gchart

= render 'nav'

%h1 All Licenses

= render 'filter', :return_to => 'chart_licenses_path'

%div#chart_div{:style => 'width: 1300px; height: 550px;' }

        

app/views/licenses/edit.html.haml
-# edit.html.haml

%h1 Edit Existing License @license.licenseId

= form_tag license_path(@license), :method => :put do

  = label :license, :ogranisationName, 'Organization Name'
  = text_field :license, 'organisationName'

  = submit_tag 'Update'

app/views/licenses/geochart.html.haml
- content_for(:head) do
  = javascript_include_tag 'http://www.google.com/jsapi'
  = javascript_include_tag :geochart

= render 'nav'

%h1 All Licenses

= render 'filter'

%div#chart_div{:style => 'width: 1300px; height: 550px;' }

        

app/views/licenses/import.html.haml
-# edit.html.haml
- if flash[:amkt_cookie]
  - content_for(:onload) do
    $('#log').load("#{import_stream_licenses_path(:amkt_cookie => flash[:amkt_cookie])}")

= render 'nav'

%h1 Import Licenses

= form_tag do_import_licenses_path, :method => :post do

  = label :vendor, :email, 'AMKT Vendor Email'
  = text_field :vendor, 'email'

  = label :vendor, :password, 'Password'
  = password_field :vendor, 'password'

  = submit_tag 'Import'

%h2 Log

%ul#log
  - @log.each do |row|
    %li= row

app/views/licenses/index.html.haml
= render 'nav'

%h1 All Licenses (#{@licenses.length}|$#{@sum})

= render 'filter', :countries => true

%table#licenses
  %thead
    %tr
      %th License Id
      %th{:class => session[:sort] == 'organisationName' ? 'hilite' : ''}
        = link_to 'Organisation Name', sort_licenses_path(:sort => :organisationName, :return_to => @current_action)
      %th Email
      %th Count
      %th Country
      %th Edition
      %th License Type
      %th{:class => session[:sort] == 'startDate' ? 'hilite' : ''}
        = link_to 'Start Date', sort_licenses_path(:sort => :startDate, :return_to => @current_action)
      %th End Date
      %th Price
  %tbody#licenselist
    - @licenses.each do |license|
      %tr
        %td= link_to license.licenseId, license_path(license)
        %td= license.organisationName
        %td= mail_to license.technicalContact.email, license.technicalContact.name
        %td= license['count']
        %td= license.technicalContactAddress.country
        %td= license.edition
        %td= license.licenseType
        %td= license.startDate
        %td= license.endDate
        %td= license['price']

- if (@current_action == 'notbought')
  - @licenses.each do |license|
    #{license.technicalContact.name} &lt;#{license.technicalContact.email}&gt;,

app/views/licenses/pivot.html.haml
- content_for(:head) do
  = javascript_include_tag 'http://www.google.com/jsapi'
  = javascript_include_tag :pivotchart

= render 'nav'

%h1 All Licenses

= render 'filter'

= render 'group'

%div#chart

%table#licenses
  %thead
    %tr
      %th Start Date
      - @all_editions.each do |edition, price|
        %th= edition
  %tbody#pivot
    %tr
      %td= 'Total Count'
      - @total.each do |edition, count|
        %td= count
    - @pivot.each do |startDate, license|
      %tr
        %td= startDate
        - @all_editions.each do |edition, price|
          %td= license[edition]

app/views/licenses/sales.html.haml
-# sales.html.haml
- if session[:amkt_cookie]
  - content_for(:head) do
    = javascript_include_tag 'http://www.google.com/jsapi'
    = javascript_include_tag :tablequerywrapper
    = javascript_include_tag :sales

= render 'nav'

%h1 Sales

= form_tag sales_update_licenses_path, :method => :post do

  = label :vendor, :email, 'AMKT Vendor Email'
  = text_field :vendor, 'email'

  = label :vendor, :password, 'Password'
  = password_field :vendor, 'password'

  = submit_tag 'Update'

%h2 Report

%div#chart

%div#table

app/views/licenses/show.html.haml
-# in app/views/licenses/show.html.haml

%h2 Details about #{@license.licenseId}

%ul#details
  %li
    Technical Contact:
    = @license.technicalContact.name
    , 
    = @license.technicalContact.email
  %li
    Dates: 
    = @license.startDate
    -
    = @license.endDate

= link_to 'Edit', edit_license_path(@license)
= link_to 'Back to licenses list', licenses_path

app/views/licenses/timeline.html.haml
- content_for(:head) do
  = javascript_include_tag 'http://www.google.com/jsapi'
  = javascript_include_tag :timeline

= render 'nav'

%h1 All Licenses

= render 'filter'

= render 'group'

%div#chart_div{:style => 'width: 1300px; height: 550px;' }

        